export const INITIAL_STATE = {
  collectionIntroView: true,
  theCity: false,
  theDesert: false,
  showAllJewels: true,
  user: '',
  email: '',
  password: '',
  message: '',
  detailView: '',
  admin: false,
  collectionOptions: [],
  newCollection: '',
  addCollection: false,
  collection: 'thecity',
  allCityPosts: [],
  allDesertPosts: [],
  detailId: '',
  title: '',
  content: '',
  file: '',
  selectedImage: null, // {}
  url: '',
  introImage: false
}
